### ISSUE TITLE
[Plugin Request]

### ISSUE THREAD

**Issue by HazelYT** [supercrafter333/PTimeUI#2]
Plugin Name: EXP Leaderboards
Plugin Info:
Create economy like plugin, but in EXP, dependent on economy api, player receives exp the amount of money they get from selling. (If player sells a diamond for $100, player receives 100 exp. /expleaderboard to set location for the leaderboard for top 10 exp holder. /myexp to show how many exp you have. If a player kills someone, receives exp, if killing the same player again, gets half of the exp before this kill. if the player dies, they lose 1% of their exp. (for kill/death exp, make them customization in config.yml). I'd appreciate if the players gets over 1000, it writes as 1k, (1573->1.57k | 248944->248.94k), 1m and 1b same way.  

Thank for reading this request, I'd appreciate it if you make this into reality! If you have any questions, feel free to reply and I'll be happy to answer :D

**Comment by supercrafter333** [comment]
You can do plugin requests on my [Discord Server](https://discord.gg/ca6cWPpERp).
